### ISSUE TITLE
Add asterisk and help text to field label

### ISSUE THREAD

**Issue by paboden** [chapter-three/require-to-publish#7]
Add Asterisk and additional text (like "Required to publish", "Field is required to publish page", etc....)

Whoever gets it added first gets to decide the text :)

**Comment by dzink** [comment]
Looks like Rocks took care of this in [this commit: 32a247](https://github.com/chapter-three/require-to-publish/commit/32a247eb8e780bdd03974f41a51360666de6d9f0)
